name: Trigger on Any Branch Push

on:
  push:
    branches:
      - '**'

jobs:
  branch-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Print Branch Name
        run: |
          echo "Branch pushed: ${{ github.ref_name }}"
