name: Hello World Workflow

on: [push]

jobs:
  say-hello,my name is:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, GitHub Actions! My name is Ramani"

